name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.18
          - 3.3.3

    steps:
      - uses: actions/checkout@v3

      - uses: coursier/cache-action@v6

      - name: setup java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin
          java-version: 21

      - uses: sbt/setup-sbt@9d56cf12e9b58d219605e1d8bfe69a8395fedde0 # v1

      - name: build ${{ matrix.scala }}
        run: sbt "++${{ matrix.scala }}; clean; check; coverage; test; coverageReport; coverageAggregate"

      - name: upload coverage
        if: success()
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: target/out/jvm/scala-${{ matrix.scala }}/conhub/coverage-report/cobertura.xml
          format: cobertura
          flag-name: Scala ${{ matrix.scala }}

      - name: slack
        uses: homoluctus/slatify@master
        if: failure() && github.ref == 'refs/heads/master'
        with:
          type: ${{ job.status }}
          job_name: Build
          url: ${{ secrets.SLACK_WEBHOOK }}