name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.16
          - 3.3.3

    steps:
      - uses: actions/checkout@v3

      - uses: coursier/cache-action@v6

      - name: scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: 17

      - name: build ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean check coverage test coverageReport coverageAggregate

      - name: upload coverage
        if: success()
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: target/scala-*/coverage-report/cobertura.xml
          format: cobertura
          flag-name: Scala ${{ matrix.scala }}

      - name: slack
        uses: homoluctus/slatify@master
        if: failure() && github.ref == 'refs/heads/master'
        with:
          type: ${{ job.status }}
          job_name: Build
          url: ${{ secrets.SLACK_WEBHOOK }}